### ISSUE TITLE
Add release for Apple Silicon

### ISSUE THREAD

**Issue by fmaclen** [fmaclen/canutin#85]

**Comment by fmaclen** [comment]
```yml
# electron-builder.yml

mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
```

This configuration didn't work when building the app on Github Actions, my _very uninformed_ guess is because in [release.yml](https://github.com/Canutin/desktop/blob/master/.github/workflows/release.yml#L12-L14) we specify `macos-latest` as the `matrix.os` strategy and that only applies to the x86 version.

Reopening it because it's not fixed.

Note that the `x86` version works well through Rosetta on Macs with Apple silicon.
